### PR TITLE
Add support for UICollectionView introspection

### PR DESCRIPTION
**Pull request by chrismaddern**
iOS 16 has migrated `List` to use `UICollectionView` under the hood (at least in some cases.)

This is a very simple addition to add support for `UICollectionView` introspection.

### CODE REVIEW

**Comment by davdroman** [comment]
Adding some tests. Will merge soon.

**Comment by chrismaddern** [comment]
oh, amazing! 🥳 

glad to be of help... and thrilled to be back on `main`

**Comment by davdroman** [comment]
@X901 yes, you will need to introspect them both separatedly.

For this particular case, I don't think you'll need to add an `#if available` condition, as it's almost always going to be one or the other. In the cases where you do need to distinguish between platforms, here's a quick workaround you can use for now:

```swift
// add this to your codebase
extension View {
	func availability<Transformed: View>(
		@ViewBuilder _ transform: (Self) -> Transformed
	) -> Transformed {
		transform(self)
	}
}

[...]

struct YourView {
	var body: some View {
		List {
			[...]
		}
		.availability {
			if #available(iOS 16, *) {
				$0.introspectTableView { tableView in
					[...]
				}
			} else {
				$0.introspectCollectionView { collectionView in
					[...]
				}
			}
		}
	}
}
```

I have some ideas on how to improve the ergonomics of introspecting the same SwiftUI component in different OS versions, but I'm yet to explore them when I get some spare time.

**Comment by fascinated** [comment]
thanks for sharing this snippet, really helped me get this working with Lists in 15 and 16. <3

**Pull request merged**
