### PR TITLE
[Misc] Fix more concurrency warnings + CI for beta platforms

### PR DESCRIPTION
**Pull request by Alex293**
This is pretty much WIP, not ready for full review, just to get feedback if someone wants to try as I make progress or contribute. 

This builds on Xcode 16 / Swift 6 and 5 mode and Xcode 15 swift 5.
Tests are passing except for one that can't find an import. I'll look into it.

Now I went for the easy path annotating quite a lot of thing with @MainActor which might simply be sendable instead. I first wanted to have something compilable and test to run. I'll check deeper now if I can avoid some MainActor requirements as one might want to use some of the conditions for code outside of swift despite this not being the main intent of the lib.

Open to feedbacks, it's my first open contribution outside of some small bug fixes.

Edit: Fixes https://github.com/siteline/swiftui-introspect/issues/418

### CODE REVIEW

**Comment by GeorgeElsham** [comment]
Fixes #418

**Comment by GeorgeElsham** [comment]
Hmm well I thought that would link the issue and this pull request but apparently not. Seems like you must say it in the pull request description. See [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by Alex293** [comment]
I finally didn’t had time to investigate further this week. I’m planning on trying things next week. @GeorgeElsham can you try this branch and telle me if you have issues in your project like over constraints to main actor ? That way I can adapt the PR before asking for review. We only use small parts of the library so I’m not sure if the choices I made à always sensible.

**Comment by GeorgeElsham** [comment]
I don't use all that much of the package. The main thing is no warnings in complete concurrency mode and no errors in Swift 6 mode. SwiftUI views are `@MainActor` by default so I suspect a lot of things will have that annotation. I'll have to check it out later (today, ideally) but this looks like a good start after skim read of the changes. I'm by no means a Swift 6 concurrency expert but I'll see what I can do.

**Comment by Alex293** [comment]
Thing is most of the api is indeed made to be used inside a SwiftUI view but I kept wondering if some should instead be Sendable to enable code outside to use parts of it. I’m not sure it makes total sense though.

**Comment by GeorgeElsham** [comment]
This builds in my project perfectly fine and removed the warnings. I'll also try to refactor from the main branch too and see if I have less reliance on `@MainActor`, otherwise if I can't simplify it this looks good to merge.

**Comment by GeorgeElsham** [comment]
I've made a new pull request which makes far less use of `@MainActor`. Let me know what you think, continuing the conversation on #424.

**Comment by davdroman** [comment]
> This builds in my project perfectly fine and removed the warnings.

If this branch fixes all the Swift 6 concurrency warnings, let's get it merged.

> I kept wondering if some should instead be Sendable to enable code outside to use parts of it. I’m not sure it makes total sense though.

We can worry about this in a separate PR.

@Alex293 mark as ready for review if you're happy with your changes.

**Comment by Alex293** [comment]
I'll rename the commits, do you prefers a signe one ? or maybe one for the Package.swift edits ?

**Comment by davdroman** [comment]
> I'll rename the commits, do you prefer a signe one ? or maybe one for the Package.swift edits ?

Doesn't matter, I'm going to squash and merge anyway.

**Pull request merged**
