### PR TITLE
Fix an issue where nested ScrollViews would not be detected properly

### PR DESCRIPTION
**Pull request by simba909**
As the title implies, this PR fixes an issue where if you have the following setup:

```swift
ScrollView {
    Text("Item 1")
    ScrollView {
        Text("Item 1")
    }
    .introspectScrollView { scrollView in
        // scrollView contains a reference to the outer ScrollView
    }
}
```

the outer `ScrollView` would always overshadow the inner. This was due to the internal code for looking up the `ScrollView` using a depth-first search instead of breadth first - causing it to skip over a potentially matching sibling in the process.

Let me know if there's anything I missed, or should add!

### CODE REVIEW

**Comment by SplittyDev** [comment]
Thanks a lot for this PR! 🎉 

Looks great so far, could you add a test for macOS too?

We also require a changelog entry for every PR. Please merge the latest master branch into the PR and add a line to the `CHANGELOG.md` file under the `master` section,, describing the fix.

Once that's done, I'll be happy to merge 👍

**Comment by simba909** [comment]
@SplittyDev Thank you for the review! I've updated the PR with the latest changes from `master`, added tests for macOS, and written a changelog entry 👍🏻

**Comment by SplittyDev** [comment]
@simba909 we just merged the new Github CI integration into this branch and sadly the macOS test for nestedScrollView is failing with the following message:

```
✗ testNestedScrollView, XCTAssertNotEqual failed: ("<SwiftUI.HostingScrollView: 0x7fa4e1116000>") is equal to ("<SwiftUI.HostingScrollView: 0x7fa4e1116000>")
```

Which suggests that the code doesn't work properly on macOS.
Could you look into this?

**Comment by simba909** [comment]
@SplittyDev Absolutely, I'll have a look!

**Comment by simba909** [comment]
Alright this should be good to go now, turns out that the behavior on macOS 10.15 matches that of iOS 13 (which makes sense I guess) so I needed to change the way that `NSScrollView`s are found on 10.15 too to make it work in the case of nested views. The tests seem to be passing correctly now, both for Big Sur and Catalina 🎉

**Review by SplittyDev — APPROVED** [review]
LGTM 🎉

**Review by JannThomas — APPROVED** [review]

**Pull request merged**
