### PR TITLE
Fix watchOS preview build issue

### LINKED ISSUE #111: cannot find type 'PlatformView' in scope
When trying to preview an Apple Watch SwiftUI View in the canvas in Xcode, I get this error:

```
SchemeBuildError: Failed to build the scheme "WatchApp"

cannot find type 'PlatformView' in scope
```

Any ideas, how to fix this?

### PR DESCRIPTION
**Pull request by sergeirr**
For some reason Xcode watchOS SwiftUI preview attempts to build this package against watchOS SDK.
Fixed by adding os type check.
Tested with:
- iOS Preview
- watchOS Preview
- iOS build
- watchOS build

Fixes #111

### CODE REVIEW

**Comment by sergeirr** [comment]
Fix for #111 
Additional description: [https://developer.apple.com/forums/thread/731732](https://developer.apple.com/forums/thread/731732)

**Comment by davdroman** [comment]
Thanks for your PR.

Is there any way we could add a CI check to make sure this doesn't break with future iterations?

**Comment by sergeirr** [comment]
I'm not sure about this. I don't know if it is possible to "Build to Preview" from the command line to reproduce the problem.

**Comment by davdroman** [comment]
Okay I'll look into this. I wouldn't want to merge without some assurance from CI. I'll try my best to get it sorted asap.

**Comment by sergeirr** [comment]
I see.
Another workaround for developers is to temporary remove the iOS main app target from the watchOS scheme when you want to work with watchOS SwiftUI Previews.
image

**Comment by sergeirr** [comment]
@davdroman You can mention me if you need some help with an example project to reproduce this.

**Comment by davdroman** [comment]
@sergeirr yes please, I'd certainly appreciate an example project.

**Comment by sergeirr** [comment]
@davdroman This is the project [https://github.com/sergeirr/WatchOSIntrospect](https://github.com/sergeirr/WatchOSIntrospect)
There are 2 branches (excluding main):

1. With issue (added origin SwiftUIIntrospect package)
2. Without issue (added forked by me SwiftUIIntrospect package)

**Comment by davdroman** [comment]
Thanks! This is very helpful to get going.

**Pull request merged**
