### PR TITLE
Fix view controller introspection

### PR DESCRIPTION
**Pull request by rzulkoski**
- Updated `UIKitIntrospectionViewController` to also use its view's moveToWindowHandler when applying customizations.
- Updated both `UIKitIntrospectionView` and `UIKitIntrospectionViewController` to set their handlers up front in their respective `makeUIView(Controller)` methods rather than delaying it until `updateUIView(Controller)` is called.

### CODE REVIEW

**Comment by davdroman** [comment]
Are there any notables changes in behavior with this approach? Is the callback invoked slightly earlier (in terms of run loops) than it would if it was added on `updateUIView`?

**Comment by rzulkoski** [comment]
Hi David, I haven't noticed any changes in behavior except that I am now able to consistently find views and view controllers.

**Comment by nashfive** [comment]
I had a similar issue with my NavigationController callbacks not being called when navigating to my Views while a fullscreen cover was being dismissed. It felt too hacky to play with artificial delays... Switching to @rzulkoski fixed all my issues and my callbacks are now called propery. 
When can these changes be incorporated ?

**Comment by danhalliday** [comment]
I can confirm this branch fixes a show-stopping bug in my project where a `NavigationView` was only being picked up about half the time.

**Comment by SplittyDev** [comment]
Looks pretty good, thanks! Wondering why the GitHub workflow isn't running..

**Comment by rzulkoski** [comment]
I think any tests related to `List` will fail due to iOS 16 switching to `UICollectionView` instead of `UITableView`.

**Comment by davdroman** [comment]
I've been granted maintainer access to this repo so I'm going to do my very best to get this merged ASAP. Right now, this PR is blocked by the issues reported in #179 so I'll try and take care of that first.

**Comment by davdroman** [comment]
@rzulkoski #179 should be fixed now. Can you push an empty commit to retrigger the CI please?

**Pull request merged**
