### PR TITLE
Fix finding UIScrollViews that are clipped(), masked or combined with clipShape() or cornerRadius()

### PR DESCRIPTION
**Pull request by paescebu**
This should fix issue:
[issues 162](https://github.com/siteline/SwiftUI-Introspect/issues/162)

Fixes:
```swift
struct ContentView: View {
    var body: some View {
        HStack {
            ScrollViewReader { proxy in
                ScrollView(.horizontal) {
                    TimeLineView()
                }
                .introspectScrollView { scrollView in
                    print(scrollView)    //closure not called when clipped or masked
                }
                .clipped()              // this caused issues
                .mask(Text("Hello"))    // or this
                .clipShape(Rectangle()) // and this
            }
        }
    }
}
```

### CODE REVIEW

**Review by kaweerutk — APPROVED** [review]
lgtm

**Review by davdroman — CHANGES_REQUESTED** [review]
This breaks CI in every platform for `testNestedScrollView`. We can't merge this until that test is fixed.

**Comment by paescebu** [comment]
> This breaks CI in every platform for `testNestedScrollView`. We can't merge this until that test is fixed.

You're right. The test also is correct. It seems that this change breaks the logic as soon as two ScrollViews are in play. 
IMO its not the tests that need to be fixed, it's the implementation itself

**Comment by paescebu** [comment]
I think I found a solution, but I feel the name of the new selector is quite verbose. Because first i will search through the hierarchy that was looked through before, and only if it doesn't find the respective ScrollView I apply the selector that goes higher up to its ancestors.

Let me know how this can be improved

**Comment by paescebu** [comment]
I also added a unit test that validates that masked or clipped ScrollViews are also found correctly. (unit tests "correctly" fail if the change is reverted)

**Comment by davdroman** [comment]
> IMO its not the tests that need to be fixed, it's the implementation itself

You're right, I misspoke 😄

**Review by davdroman — APPROVED** [review]
Great effort, @paescebu 👏

**Comment by paescebu** [comment]
thank you @davdroman!
Was my first contribution to another open source library :D Happy to help

**Pull request merged**
