### PR TITLE
Improve unit testing to catch unwanted behavior changes

### PR DESCRIPTION
**Pull request by jevonmao**
**Problem**
Except for the `TextField`, most of the other UI component's tests simply use `XCExpectation` to check that the Introspect closure is being called without any assertion on the content of the closure parameter. Malicious code such as replacing an existing selector search with a dummy class like `UIColorWell()` does not fail the test. 

**Solution**
This pull request improved unit tests for several different UI components, referencing the `TextField`'s implementation. I have tested the improved tests, and they are able to catch unwanted behavior changes. I tried my best to minimize any unnecessary code changes, and follow existing patterns and conventions.

### CODE REVIEW

**Comment by SplittyDev** [comment]
Looks great so far! Thanks a lot for contributing ✨

**Comment by jevonmao** [comment]
@SplittyDev Hi there, sorry about the long delay. But I plan to finish this pull request which I started. All the unit tests are passing on my machine, yet they fail on the CI/CD workflow. Can you take a look?

**Comment by SplittyDev** [comment]
@jevonmao no worries! We'll take a look as soon as possible :) Tests on the CI have been flaky in the past, hopefully it's not too hard to fix this time 😁

**Comment by SplittyDev** [comment]
image

This is the failing test. No idea what's going on there. I'll check it out locally.

**Comment by jevonmao** [comment]
Yes please do that, because when I run it locally it passed.

**Comment by SplittyDev** [comment]
Hi @jevonmao, I tested this locally under different configuration and I can't find anything wrong with it. Could you remove the `Gemfile.lock` changes and push again? For some reason GitHub refuses to re-run the workflow, so you'll have to push from your fork.

**Comment by jevonmao** [comment]
@SplittyDev  

>  Could you remove the Gemfile.lock changes and push again?

You know when the CI previously failed, I saw something related to outdated dependencies in the error message. So I did an update command. That might be the reason why CI is failing but I think it's unlikely because it failed even before my change.

I reverted the changes. Also thank you for looking into this issue, I appreciate you guys looking into this with me.

**Comment by davdroman** [comment]
This looks like a very nice improvement. @jevonmao I know this is quite old but would you be willing to rebase your branch and update your PR and I'll get it merged asap?

For context, I've gotten rid of `Gemfile.lock` (#185) and overall strengthened our CI to run tests on iOS 14-16 so these changes would be very welcomed.

**Comment by jevonmao** [comment]
@davdroman Yes, thanks for reaching out, that would be great. I will see if I can merge master into this branch.

**Comment by davdroman** [comment]
Obsoleted by the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect/blob/master/docs/SwiftUIIntrospect.md) module tests.

**Pull request closed without merging**
