### PR TITLE
Fix concurrency warnings

### LINKED ISSUE #418: Swift 6 complete concurrency warnings
### Description

After updating to Swift 6 with complete concurrency checking following [Migrate your app to Swift 6](https://developer.apple.com/videos/play/wwdc2024/10169), I am getting multiple warnings. One on a `List` looks like so:

> Static property 'v17' is not concurrency-safe because non-'Sendable' type 'PlatformViewVersion<iOSVersion, ListType, UICollectionView>' may have shared mutable state; this is an error in the Swift 6 language mode

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

### Expected behavior

It should compile with no warnings or errors.

### Actual behavior

Xcode produces warnings.

### Steps to reproduce

Example code:

```swift
.introspect(.list, on: .iOS(.v17)) { list in
    /* ... */
}
```

### Version information

1.1.4

### Destination operating system

iOS 18.0

### Xcode version information

Version 16.0 beta (16A5171c)

### Swift Compiler version information

```shell
swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0
```

### PR DESCRIPTION
**Pull request by GeorgeElsham**
An alternative to #422.

Fixes #418.

### CODE REVIEW

**Comment by GeorgeElsham** [comment]
One thing I notice that's a bit different to #422's attempt is the `Package.swift`. Is there any information on what this is (being having a 6.0 version) about and is it needed / should I also include it here?

**Comment by Alex293** [comment]
@GeorgeElsham I think you used the Swift6 compiler in Swift 5 mode, this definitively not build on my side with Swift 6

**Comment by Alex293** [comment]
What I did with the Package.swift file allows working with previous compiler versions and in both languages versions. Note that there is Package@swift-5.7.0 too.

**Comment by GeorgeElsham** [comment]
@Alex293 You're right, I see. I'll try to fix it, thank you.

**Comment by Alex293** [comment]
I think we should gather the opinion of the author and the community if there is interest in using some of the constructs outside of SwiftUI. If not, I don’t think there is much sense in spending effort going further than what I did in the other branch. Did you identify any use cases for non main actor but sendable apis in this repo ?

**Comment by Alex293** [comment]
@davdroman can I ask your opinion ? Do you know about any potential use of this lib APIs outside of of SwiftUI/MainActor ?

**Comment by davdroman** [comment]
@Alex293 not off the top of my head, I'd find it strange that anyone would want to employ introspection in a background thread.

**Comment by GeorgeElsham** [comment]
@Alex293 Unfortunately I've had pretty limited time, but I've fixed the issues. It still uses `@MainActor` only when appropriate. I've tested using Xcode 15.4 Beta and Xcode 16.0 Beta. Let me know if there are still any problems.

**Comment by c0dedbear** [comment]
Hello guys, when are you planning to merge this into the main? From Xcode 16 Beta 3 and Swift 6 mode those warnings are errors.

**Comment by Alex293** [comment]
I can speak for the maintainers so no merge ETA from me but you can use my fork in the mean time (I'd be glad if you could at leat try it to see if there are any thing I missed).

Last time I checked, this branch still missed some annotations for things being spi or similar, I can't remember. TBH I'm slightly annoyed to review this branch as I already did the work on another branch and asked which direction to pursue before continuing investing time on any of the branches. I'll wait for the maintainers to chime in and try to contribute any whatever direction they prefer.

**Comment by c0dedbear** [comment]
> I can speak for the maintainers so no merge ETA from me but you can use my fork in the mean time (I'd be glad if you could at least try it to see if there are any thing I missed).
> 
> Last time I checked, this branch still missed some annotations for things being spi or similar, I can't remember. TBH I'm slightly annoyed to review this branch as I already did the work on another branch and asked which direction to pursue before continuing investing time on any of the branches. I'll wait for the maintainers to chime in and try to contribute any whatever direction they prefer.

It's seems like your fixes have eliminated errors and warnings. btw stay tuned for maintainer(s)...

**Pull request merged**
